language: java
env:
  global:
    # COVERITY_SCAN_TOKEN
    - secure: UYBQVziOzbe5mGrE9y7rcXxYA2Kxzce77Jj2M/ptbWoHAALtjdrddu+3tIjkjdT4jr8af8G+L6qLet17fw411id5WD9W5g7oxZGfaak7YY9pJHt/v4E3SZUtLDZs8ukWnDz4Ry7XbGR+CMFpLRGTEDjCjCaC/3umH3z082I27JsqIj2AhsWIcJ1liNZcasiB9shLhNqkY2YEnpMrssKvaHBs2NTpExO8raNXF1pFOCiskbEqqT8fkgfQ1AyELd+qZL7Lxapnm0ROg+zncOu9IupHeSPFulEdMC4rM66aoKoYnLNyEusLPXJLMLpEo39k4QwhA7cdrRMrkbsZ/KEjWjvvmOCPq74EdeD9nSgOM950LLx6c1+P9v2EdzA67CmG2oXhfLVmOXvG8ngleqFCTuFPv4XTwrQL6qHS6tStypmpfgHkfyTOzKCfd2i/jeMgeuMpOFHRC4hAJ0eb9pdvKGVUDW1FjzrVUm4SgvrWkAtNTW4OMnAHs4s5UnpDh6PkRzG9kBJp/pNnLELJYGiyhxWeC0zny2S/l9owG5tuodVXZCBmAsjH1EqMtoQZoRhw/nTJvc/+oNqXW+WJTfMsRBcOjWp9Bj7p6hjZ2V1KZXun1UZv38/PVpS0hefTW1CvsyjO1Ly8CZB/IG0EaWwHYf6D56p0TGYRCeQbEL8c5FU=

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

before_script:
  - pip install --user codecov

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

after_success:
  - codecov

addons:
  coverity_scan:
    project:
      name: itsallcode/openfasttrace
      version: 0.1.0
      description: OpenFastTrace requirement tracing
    notification_email: christoph@users.sourceforge.net
    build_command_prepend: mvn clean
    build_command: mvn -DskipTests=true compile
    branch_pattern: coverity_scan
  sonarcloud:
    organization: "itsallcode"
    token:
      secure: PIBpZXZFDv7DNJxHb56Ejcoph+cRZ7T7+iBl/pFrwD3Ldyba0d8K6h/SCPD2aXAiyO+/vB74wW/V2FYkl69QjFwKYdD1/7RpGV+ilurSh16Q4LzNke3uHGHk+0OMMQDlqNdrrYVLZImCx2YuqPJ8AFC50C/4yqZtnUfqi9Cy5YXOKvnsoxJIVSAA1Vqxd+2hJ8/BeMoeWU44Wy4b5jG0TuprcGxR15zZwvZPmiKCkNZQ5P+Dc4E4h3D7tLQLa3n2omw14tuVJqRNWp5VijMdWott5RkigCgHNsGG4XGj3iLLq2HZDwGzwKx3f2TWRpyGS6p2Q9rxD14g4igH+Jklin9qiZLn3IieOWIg2XcyHyeU2OFYsqbFxufZUQUCcPMfZZHAES8DgYQtiuO4l0M2SNhJ6qR22YZpyljVb8wU9qj55iYiWpuNKWr9XmzQXGE2xp4friPcFAmHgbZWjM1kRYwY49gMadJhbk4RXqObY1IBrWyPhQARoUfPRUnMD9wEMabgZo6czSNkotk+OYS60wkg3URmu0EB96UtRq/1y9/4D5X5DExmAeXuVHcuQrdHxeZt0/F3XhGkR5Sgic/soe8CJE5nMW/js82/gvT1lmMTJ79riJw8PVvC4/dtaMCqZ8lGVUz5gl6JQG21kw2yZ2+0r9lNmvWhLej7U6wNxNk=
