language: java

env:
  global:
    # COVERITY_SCAN_TOKEN
    - secure: UYBQVziOzbe5mGrE9y7rcXxYA2Kxzce77Jj2M/ptbWoHAALtjdrddu+3tIjkjdT4jr8af8G+L6qLet17fw411id5WD9W5g7oxZGfaak7YY9pJHt/v4E3SZUtLDZs8ukWnDz4Ry7XbGR+CMFpLRGTEDjCjCaC/3umH3z082I27JsqIj2AhsWIcJ1liNZcasiB9shLhNqkY2YEnpMrssKvaHBs2NTpExO8raNXF1pFOCiskbEqqT8fkgfQ1AyELd+qZL7Lxapnm0ROg+zncOu9IupHeSPFulEdMC4rM66aoKoYnLNyEusLPXJLMLpEo39k4QwhA7cdrRMrkbsZ/KEjWjvvmOCPq74EdeD9nSgOM950LLx6c1+P9v2EdzA67CmG2oXhfLVmOXvG8ngleqFCTuFPv4XTwrQL6qHS6tStypmpfgHkfyTOzKCfd2i/jeMgeuMpOFHRC4hAJ0eb9pdvKGVUDW1FjzrVUm4SgvrWkAtNTW4OMnAHs4s5UnpDh6PkRzG9kBJp/pNnLELJYGiyhxWeC0zny2S/l9owG5tuodVXZCBmAsjH1EqMtoQZoRhw/nTJvc/+oNqXW+WJTfMsRBcOjWp9Bj7p6hjZ2V1KZXun1UZv38/PVpS0hefTW1CvsyjO1Ly8CZB/IG0EaWwHYf6D56p0TGYRCeQbEL8c5FU=

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

before_script:
  - pip install --user codecov

after_success:
  - codecov

addons:
  coverity_scan:
    project:
      name: hamstercommunity/openfasttrack
      version: 0.1.0
      description: OpenFastTrack
    # notification_email: scan_notifications@example.com
    build_command_prepend: mvn clean
    build_command: mvn
    branch_pattern: coverity_scan
