language: java
env:
  global:
    # COVERITY_SCAN_TOKEN
    - secure: UYBQVziOzbe5mGrE9y7rcXxYA2Kxzce77Jj2M/ptbWoHAALtjdrddu+3tIjkjdT4jr8af8G+L6qLet17fw411id5WD9W5g7oxZGfaak7YY9pJHt/v4E3SZUtLDZs8ukWnDz4Ry7XbGR+CMFpLRGTEDjCjCaC/3umH3z082I27JsqIj2AhsWIcJ1liNZcasiB9shLhNqkY2YEnpMrssKvaHBs2NTpExO8raNXF1pFOCiskbEqqT8fkgfQ1AyELd+qZL7Lxapnm0ROg+zncOu9IupHeSPFulEdMC4rM66aoKoYnLNyEusLPXJLMLpEo39k4QwhA7cdrRMrkbsZ/KEjWjvvmOCPq74EdeD9nSgOM950LLx6c1+P9v2EdzA67CmG2oXhfLVmOXvG8ngleqFCTuFPv4XTwrQL6qHS6tStypmpfgHkfyTOzKCfd2i/jeMgeuMpOFHRC4hAJ0eb9pdvKGVUDW1FjzrVUm4SgvrWkAtNTW4OMnAHs4s5UnpDh6PkRzG9kBJp/pNnLELJYGiyhxWeC0zny2S/l9owG5tuodVXZCBmAsjH1EqMtoQZoRhw/nTJvc/+oNqXW+WJTfMsRBcOjWp9Bj7p6hjZ2V1KZXun1UZv38/PVpS0hefTW1CvsyjO1Ly8CZB/IG0EaWwHYf6D56p0TGYRCeQbEL8c5FU=

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache

before_script:
  - pip install --user codecov

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

after_success:
  - codecov

addons:
  coverity_scan:
    project:
      name: itsallcode/openfasttrace
      version: 0.1.0
      description: OpenFastTrace requirement tracing
    notification_email: christoph@users.sourceforge.net
    build_command_prepend: mvn clean
    build_command: mvn -DskipTests=true compile
    branch_pattern: coverity_scan
  sonarcloud:
    organization: "itsallcode"
    token:
      secure: "stET2mlxtWuTjhrgBC1xO77FHuyF7E7tf+9CY9W9TEUS5UlTNVr9/gzu3p4VeWU7knpiq4PuPabPCAFfbZaPF9vMP0lO6qKvsrd0RBnCIYn2l6AEMKzd0M1yksSBvUnS+7LoT8+qkJ7hPxzSkgM7oWCsHzp//gFvr7r1+n2B9QxrsjpAPqmZlU+0cthX4cy6yIVgMG6T1TlBORcNx9TTZ+ppGLoBJ7PTL04R1GNbNy0IExlegO6JRGo6T2uURr5UkrWeKVlRZY0u3VDs6OUahE3g2srJZPruedX9KRa4XLztTLXYmOUO/6XFxxfx/eqpWqD68Eal/IguTVibPiU0dCpXsTvWE/bO1dDolBxu9afKI7ntNWmIbfKpIT0bRypz+Ss12A9cw3bNJYRXkbA4sfsMmI4kcAhdl+P0bgfyWlmwXE8z+akOOEzkHZ2vT28WVZ27KkByTtl64uWqweeAwPLQN3ORcilyt9Ip+u1Z/sZUaRuXFMi5pciB3lfLq5Bm1bu2VDep2XLQnZD+KPp5+YHCxVrXBy0quDMNYU18R/OSWfqkCOPkklopG02ngvQAYHeezJILqnlS7bD6ujdthv/97LM39W8heFxxUOQiXKw+zWccFTS+lMChX+8n5+xFoJV1NjlGv1rz5PAcUCudCTHu5Pk/2H6XFcTq9/6Ysds="
    branches:
      - master
      - develop
      - task/82-Rename_project_to_openfastrace
